# Generated by Django 6.0.7 on 2026-07-13 20:51

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokWeeklyReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('snapshot_date', models.DateField(help_text='The date this snapshot was generated on.')),
                ('pdf_file', models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='tiktok_reports/')),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('views_total', models.PositiveIntegerField(default=0)),
                ('likes_total', models.PositiveIntegerField(default=0)),
                ('comments_total', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
